WCTS/WCTS/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCMS_MAIN.HelperClass;
using WCTS.Models;
using WCTS.Models.EntityModel;
using WCTS.Repository;

namespace WCTS.Controllers
{
    public class CommonController : Controller
    {
        private readonly Dictionary<int, SessionData> _sessiondictionary = SessionData.GetSessionValues();
        private readonly ProductionRepository _productionRepository = new ProductionRepository();
        private readonly NotificationRepository _notificationRepository = new NotificationRepository();
        readonly Repository.Common _commonRepo = new Repository.Common();
        //
        // GET: /Common/
        public ActionResult Index()
        {
            return View();
        }


        public JsonResult GetShifts()
        {
            var eList = new List<Shift>();
            try
            {
                eList = _commonRepo.GetShifts().ToList();

            }
            catch (Exception ex)
            {
                throw;
            }
            var objstate = eList.Select(x => new { value = x.ShiftName , Id = x.ShiftId }).ToList();
            return Json(objstate.ToArray(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetModelsFromOracle()
        {
            var eList = new List<OracleModel>();
            try
            {
                eList = _commonRepo.GeModelDataFromOracle().ToList();

            }
            catch (Exception ex)
            {
                var err = eList.Select(x => new { value = ex, Id = "" }).ToList();
                return Json(err.ToArray(), JsonRequestBehavior.AllowGet);
            }
            var objstate = eList.Select(x => new { value = x.Model, Id = x.Model }).ToList();
            return Json(objstate.ToArray(), JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetSfgcodeFromOracle()
        {
            var eList = new List<OracleModel>();
            try
            {
                eList = _commonRepo.GeModelDataFromOracle().ToList();

            }
            catch (Exception ex)
            {
                var err = eList.Select(x => new { value = ex, Id = "" }).ToList();
                return Json(err.ToArray(), JsonRequestBehavior.AllowGet);
            }
            var objstate = eList.Select(x => new { value = x.ItemCode, Id = x.ItemCode }).ToList();
            return Json(objstate.ToArray(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetFgcodeFromOracle()
        {
            var eList = new List<OracleModel>();
            try
            {
                eList = _commonRepo.GeModelDataFromOracle().ToList();

            }
            catch (Exception ex)
            {
                var err = eList.Select(x => new { value = ex, Id = "" }).ToList();
                return Json(err.ToArray(), JsonRequestBehavior.AllowGet);
            }
            var objstate = eList.Select(x => new { value = x.ItemCode, Id = x.ItemCode }).ToList();
            return Json(objstate.ToArray(), JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetQcTrackingLotInfo(string lotNumber)
        {
            var data = new QcLotTracking();
            try
            {
              var  dataFetch = _commonRepo.GetQcTrackingLotInfo(lotNumber);
                if (dataFetch == null)
                {
                    data.LotNumber = "null";
                }
                else
                {
                    data = dataFetch;
                }

            }
            catch (Exception ex)
            {
                throw;
            }
           // var objstate = eList.Select(x => new { value = x.ShiftName , Id = x.ShiftId }).ToList();
            return Json(data, JsonRequestBehavior.AllowGet);
        }



        public JsonResult GetShiftsDetails()
        {
            var eList = new List<Shift>();
            try
            {
                eList = _commonRepo.GetShifts().ToList();

            }
            catch (Exception ex)
            {
                throw;
            }

            return Json(eList.ToArray(), JsonRequestBehavior.AllowGet);
        }



        public JsonResult GetLines()
        {
            List<Line> eList;
            try
            {
                eList = _commonRepo.GetLines().ToList();

            }
            catch (Exception ex)
            {
                throw;
            }
            var objstate = eList.Select(x => new { value = x.LineName, Id = x.LineId }).ToList();
            return Json(objstate.ToArray(), JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetCategories()
        {
            List<Category> eList;
            try
            {
                eList = _commonRepo.GetCategories().ToList();

            }
            catch (Exception ex)
            {
                throw;
            }
            var objstate = eList.Select(x => new { value = x.CategoryName, Id = x.CategoryCode }).ToList();
            return Json(objstate.ToArray(), JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetModels()
        {
            List<Model> eList;
            try
            {
                eList = _commonRepo.GetModels().ToList();

            }
            catch (Exception ex)
            {
                throw;
            }
            var objstate = eList.Select(x => new { value = x.ModelName, Id = x.Id }).ToList();
            return Json(objstate.ToArray(), JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetModelInformationByName(string model)
        {
            Model modelobj = null;
            try
            {
                modelobj = _commonRepo.GetModels().FirstOrDefault(a => a.ModelName == model);

            }
            catch (Exception ex)
            {
                return Json(modelobj, JsonRequestBehavior.AllowGet);
            }

            return Json(modelobj, JsonRequestBehavior.AllowGet);
        }





        public JsonResult GetInventoryTypes()
        {
            List<InventoryType> eList;
            try
            {
                eList = _commonRepo.GetInventoryTypes().ToList();

            }
            catch (Exception ex)
            {
                throw;
            }
            var objstate = eList.Select(x => new { value = x.InventoryType1, Id = x.Id }).ToList();
            return Json(objstate.ToArray(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllLotNumbers()
        {
            List<ProductionModel> eList;
            try
            {
                eList = _commonRepo.GetAllLotNumbers().GroupBy(a => new {a.LotNo}).Select(b => new ProductionModel()
                {
                    LotNo = b.Key.LotNo

                }).ToList();

            }
            catch (Exception ex)
            {
                throw;
            }
            var objstate = eList.Select(x => new { value = x.LotNo, Id = x.LotNo }).ToList();
            return Json(objstate.ToArray(), JsonRequestBehavior.AllowGet);
        }



      //  [OutputCache(NoStore = true, Location = System.Web.UI.OutputCacheLocation.Client, Duration = 2)]
        //public ActionResult GetWctsNotification(string type)
        //{
        //    var userId = (long)_sessiondictionary[1].Id;
            
        //    var roleId = _sessiondictionary[15].Id;

        //    object recentnotifications = null;
        //    // var recentNotifications = _brandManager.GetRecentActivites();
        //    var recentNotifications = _notificationRepository.GetWctsNotification(new NotificationModel() { UseId = userId, RoleId = roleId });

        //    if (type == "S")
        //    {
        //        recentnotifications = recentNotifications.Take(30).ToList();

        //    }
        //    if (type == "A")
        //    {
        //        recentnotifications = recentNotifications.Take(50).ToList();

        //    }
        //    ViewBag.recentNotifications = recentnotifications;
        //    ViewBag.TotalNotifications = recentNotifications.Count;


        //    return PartialView("_PartialNotification");
        //}



	}
}

WCTS/WCTS/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using BR_BLL;
using WCMS_MAIN.HelperClass;
using WCTS.Helper_Model;
using WCTS.Models;
using WCTS.Models.EntityModel;
using WCTS.Repository;

namespace WCTS.Controllers
{
    public class InventoryController : Controller
    {
        //
        // GET: /Inventory/

        readonly Dictionary<int, SessionData> _sessiondictionary = SessionData.GetSessionValues();
        readonly ProductionRepository _productionRepository = new ProductionRepository();
        readonly InventoryRepository _inventoryRepository = new InventoryRepository();
        readonly Repository.Common _common = new Repository.Common();
        public ActionResult Inventory()
        {
            return View();
        }


        public ActionResult InventoryReady()
        {
            return View();
        }

        public JsonResult GetMasterBarcodeData(string masterBarCode)
        {
            var userId = (long) _sessiondictionary[1].Id;
            var userName = _sessiondictionary[2].Name;
            var employeeId = _sessiondictionary[3].Name;
            var lineId = _sessiondictionary[8].Id;

            var result = new Result();
            var isExists = _inventoryRepository.GetInventoryInfo(new Inventory { MasterBarCode = masterBarCode }).Any();


            if (isExists)
            {

                return Json(new { data = result, status = "0",message="Already Received" }, JsonRequestBehavior.AllowGet);

            }


            else
            {
                var masterBarcodeData = _inventoryRepository.GetMasterBarcodeData(masterBarCode);
                return Json(new { data = masterBarcodeData, status = "1", message = "Received Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }



        public JsonResult GetPassedItemFromInventoryWD()
        {

            var list = _inventoryRepository.GetPassedItemFromInventoryWD().ToList();

            var overAlllist = new List<Models.ProductionModel>();

            foreach (var items in list)
            {
                var timeSpan = DateTime.Now.Minute;


                if (timeSpan < Convert.ToInt32(items.Min))
                {
                    timeSpan = timeSpan + Convert.ToInt32(items.Min);

                }
                var diff = timeSpan - Convert.ToInt32(items.Min);
                var overAlll = new Models.ProductionModel();
                overAlll.MasterBarCode = items.MasterBarCode;

                overAlll.Total = items.Total;

                if (diff == -1 || diff == 0)
                {

                    overAlll.RemainTime = 20 - 1;
                }

                if (diff < 0)
                {

                    overAlll.RemainTime = Math.Abs(diff);

                }

                else
                {
                    overAlll.RemainTime = 20 - diff;

                }


                if (overAlll.RemainTime < 0)
                {
                    overAlll.RemainTime = Math.Abs(overAlll.RemainTime);

                }

                // overAlll.Total = items.Total;

                overAlllist.Add(overAlll);
            }




            return Json(new { data = overAlllist }, JsonRequestBehavior.AllowGet);


        }

        public JsonResult GetPassedItemFromInventory(string fromdate, string todate)
        {

            var list = _inventoryRepository.GetPassedItemFromInventory(fromdate, todate).ToList();

            var overAlllist = new List<Models.ProductionModel>();

            foreach (var items in list)
            {
                var timeSpan = DateTime.Now.Minute;
                var diff = timeSpan - Convert.ToInt32(items.Min);
                var overAlll = new Models.ProductionModel();
                overAlll.MasterBarCode = items.MasterBarCode;

                overAlll.Total = items.Total;

                if (diff == -1 || diff == 0)
                {

                    overAlll.RemainTime = 20-1;
                }

                if (diff < 0)
                {

                    overAlll.RemainTime = Math.Abs(diff);

                }

                else
                {
                    overAlll.RemainTime = 20-diff;
             
                }


                if (overAlll.RemainTime < 0)
                {
                    overAlll.RemainTime = Math.Abs(overAlll.RemainTime);

                }
               
                // overAlll.Total = items.Total;

                overAlllist.Add(overAlll);
            }




            return Json(new { data = overAlllist }, JsonRequestBehavior.AllowGet);


        }

        public JsonResult InventoryReceived(List<ProductionModel> inventoryList)         
        {

            var userId = (long)_sessiondictionary[1].Id;
            var result = new Result();

            if (userId != 0)
            {
                try
                {
                    result.IsSuccess = _inventoryRepository.InventoryReceived(inventoryList,userId);

                }
                catch (Exception)
                {
                    result.Message = "error occured while saving the information";
                    return Json(result);
                }


                return Json(result);
            }

            else
            {
                return Json(new Result { Id = "0" });

            }




           // return Json(checkedResult);

        }

       [HttpPost]
       [AllowAnonymous]
        public JsonResult InventoryPassedItemsMove()
        {
            var passedInventoryInsertresult = new Result();
            var passedItemUpdateresult = new Result();
            var list = new List<PassedInventory>();
           
                try
                {
                    var passedData= _inventoryRepository.GetPassedItemToPrepareForInventory().ToList();
                    if (passedData.Count > 0)
                    {
                        foreach (var data in passedData)
                    {
                        var isExistsinPassedInventory = _inventoryRepository.IsExistsInPassedInventory(data.Barcode.Trim());
                        if (!isExistsinPassedInventory)
                        {
                            var passedInventoryModelData=new PassedInventory();
                            passedInventoryModelData.ProjectSetupId = data.ProjectSetupId;
                            passedInventoryModelData.Model = data.Model;
                            passedInventoryModelData.ShiftId = data.ShiftId;
                            passedInventoryModelData.CategoryCode = data.CategoryCode; 
                            passedInventoryModelData.ItemCode = data.ItemCode;
                            passedInventoryModelData.Barcode = data.Barcode;
                            passedInventoryModelData.MasterBarcode = data.MasterBarcode;
                            passedInventoryModelData.ProductionDate = data.ProductionDate;
                            passedInventoryModelData.IsHold = false;
                            passedInventoryModelData.IsMovedToFinalInventory = false;
                            passedInventoryModelData.PassedDate = data.PassedDate;
                            passedInventoryModelData.ScannedBy = data.AddedBy;
                            passedInventoryModelData.ScannedDate = data.AddedDate;
                            passedInventoryModelData.AddedBy = 9911;
                            passedInventoryModelData.AddedDate = DateTime.Now;
                            list.Add(passedInventoryModelData);
                        }
                    }


                    passedInventoryInsertresult.IsSuccess = _inventoryRepository.InventoryPassedItemsInsert(list);

                    if (passedInventoryInsertresult.IsSuccess)
                    {

                        passedItemUpdateresult.IsSuccess=_inventoryRepository.UpdateProductionMasterMovedItems(list);


                    }

                    else
                    {
                        passedInventoryInsertresult.Message = "error occured while saving the information";
                   

                    }

                    }


                }
                catch (Exception)
                {
                    passedItemUpdateresult.Message = "error occured while saving the information";
                    return Json(passedItemUpdateresult);
                }


                return Json(passedItemUpdateresult);
            }

            // return Json(checkedResult);



       public JsonResult HoldPassedInventoryItems(PassedInventoryHold passedInventoryHold)
       {

           var userId = (long)_sessiondictionary[1].Id;
           var result = new Result();

           if (userId != 0)
           {
               try
               {
                   result.IsSuccess = _inventoryRepository.HoldPassedInventoryItems(passedInventoryHold, userId);

               }
               catch (Exception)
               {
                   result.Message = "error occured while saving the information";
                   return Json(result);
               }


               return Json(result);
           }

           else
           {
               return Json(new Result { Id = "0" });

           }
           // return Json(checkedResult);

       }

        }

    }

WCTS/WCTS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>@ViewBag.Title - WCTS</title>
    @Styles.Render("~/Content/css")   
    @Scripts.Render("~/bundles/jquery")
    <link href="~/Content/bounce.css" rel="stylesheet" />
    <style>
        .transition {
            -webkit-transform: scale(1.2);
            -moz-transform: scale(1.2);
            -o-transform: scale(1.2);
            transform: scale(1.2);
        }

         
    </style>
   
</head>
<body>
   
    
    <div class="wrapper ">
        


        @Html.Partial("_PartialSidebar")
        <div class="main-panel">
            <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent" style="background-color: #FFFFFF !important">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        @*<marquee behavior=ALTERNATE style="width: 400px; text-shadow: 2px 2px 4px #008b8b; "><p style="font-weight: bold;" class="tasss" id="tass">Walton Compressor Tracking System</p></marquee>*@ 
                    
                    
                       
                    </div>
                   
                    

                    <div class="clock" style=" zoom: 0.5; font-size: 10px !important;width: auto !important"></div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                    </button>
                    <a id="url" style="color: red;font-weight: bold;text-decoration: underline" href="http://192.168.118.175/Display.html" target="_blank">Click To View Display!</a> 
                    @*<div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="navbar-nav">

                            <li role="" class="dropdown" id="wctsNotification" style="border-radius: 20px;border :1px solid orange;text-align: center">

                                @Html.Partial("~/Views/Shared/_PartialNotification.cshtml")

                            </li>
                        </ul>
                    </div>*@
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="navbar-nav">
                           
                            
                          
                            
                            

                            <li class="nav-item btn-rotate dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-cogs"></i>

                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    @*<a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>*@
                                    <a class="dropdown-item" href="@Url.Action("ChangePassword", "Account")">Change Password</a>
                                    <a class="dropdown-item" href="@Url.Action("LogOut", "Account")">Log Out</a>
                                  
                                </div>
                            </li>
                            
                            <li class="nav-item" style="border: 2px solid brown;border-radius: 10px;">
                                <a class="nav-link btn-magnify">
                                    <p>
                                        <span style="color: black !important" class="">User ID: @Session["WCTSUserName"]</span>
                                    </p>
                                </a>
                            </li>
                            @*<li class="nav-item">
                            <a class="nav-link btn-rotate" href="#pablo">
                                <i class="nc-icon nc-settings-gear-65"></i>
                                <p>
                                    <span class="d-lg-none d-md-block">Account</span>
                                </p>
                            </a>
                        </li>*@
                        </ul>
                    </div>
                </div>
            </nav>
            
            
            <div class="content">

                <div id="body">

                    @RenderBody()

                </div>

            </div>




            <footer class="footer footer-default">
                <div class="container-fluid">
                    <div class="row">
                        <nav class="footer-nav">
                            @*<ul>
                                <li>
                                    <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>
                                </li>
                                <li>
                                    <a href="http://blog.creative-tim.com/" target="_blank">Blog</a>
                                </li>
                                <li>
                                    <a href="https://www.creative-tim.com/license" target="_blank">Licenses</a>
                                </li>
                            </ul>*@
                        </nav>
                        <div class="credits ml-auto">
                            <span class="copyright">
                                ©
                                <script>
                                    document.write(new Date().getFullYear())
                                </script>  Walton Group
                            </span>
                        </div>
                    </div>
                </div>
            </footer>

        </div>


    </div>
  
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    @*<script src="~/Scripts/flipclock.min.js"></script>*@
    <script>
        var keepSessionAlive = false;
        var keepSessionAliveUrl = null;

        function SetupSessionUpdater(actionUrl) {
           
            keepSessionAliveUrl = actionUrl;
            var container = $("#body");
            container.mousemove(function () { keepSessionAlive = true; });
            container.keydown(function () { keepSessionAlive = true; });
            CheckToKeepSessionAlive();
        }

        function CheckToKeepSessionAlive() {
           
            //setTimeout(KeepSessionAlive(), 30000);
            KeepSessionAlive();
        }

        function KeepSessionAlive() {
            
            if (keepSessionAlive) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("KeepSessionAlive", "Home")',
                    success: function () { keepSessionAlive = false; }
                });
            }
            //CheckToKeepSessionAlive();
        }
        setInterval(function () { SetupSessionUpdater(); }, 30000);

      
        function testooo() {

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("InventoryPassedItemsMove", "Inventory")',
                    success: function () { keepSessionAlive = false; }
                });
            
            //CheckToKeepSessionAlive();
        }
        setInterval(function () { testooo(); }, 50000);


        $(document).ready(function () {
            $('#url').hover(function () {
                $("#url").addClass('transition');

            }, function () {
                $("#url").removeClass('transition');
            });
            //LoadNotification();
            // $('#brandNotification').load('/../Brand/GetBrandNotification/?type=S');
        });
       // setInterval(LoadNotification, 6000);

        @*function LoadNotification() {

            var link = '@Url.Action("GetWctsNotification", "Common", new { type = "replace" })';
            link = link.replace("replace", 'S');
            $('#wctsNotification').load(link);
        }*@
    </script>









</body>
</html>

WCTS/WCTS/Views/Shared/_PartialSideBar.cshtml
@using WCTS.Models

   <div class="sidebar card-header-info" style="color: white;" data-background-color="white" data-active-color="danger">
    <div class="logo">
        <a href="#" class="simple-text logo-mini">

        </a>

        <a href="#" class="simple-text logo-normal">
            WCTS
        </a>
    </div>
    @*<div class="logo">

        </div>*@

    @*<div class="logo">
            <a href="#" class="simple-text logo-mini">
                CT
            </a>

            <a href="#" class="simple-text logo-normal">
                Creative Tim
            </a>
        </div>*@
    <div class="sidebar-wrapper ps ps--active-x ps--active-y">
        @*<div class="user">
                <div class="info">
                    <div class="photo">
                        <img src="../../assets/img/faces/face-2.jpg">
                    </div>

                    <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                        <span>
                            Chet Faker
                            <b class="caret"></b>
                        </span>
                    </a>
                    <div class="clearfix"></div>

                    <div class="collapse" id="collapseExample">
                        <ul class="nav">
                            <li>
                                <a href="#profile">
                                    <span class="sidebar-mini">Mp</span>
                                    <span class="sidebar-normal">My Profile</span>
                                </a>
                            </li>
                            <li>
                                <a href="#edit">
                                    <span class="sidebar-mini">Ep</span>
                                    <span class="sidebar-normal">Edit Profile</span>
                                </a>
                            </li>
                            <li>
                                <a href="#settings">
                                    <span class="sidebar-mini">S</span>
                                    <span class="sidebar-normal">Settings</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>*@
        <ul class="nav">

            @if (Session["AllMenus"] != null)
            {
                var menuMaster = (List<MenuModel>)Session["AllMenus"];
                var groupByMenu = menuMaster.GroupBy(x => x.MainMenuName).ToList();


                foreach (var MenuList in groupByMenu)
                {

                    var urlLink = (MenuList.Key).Replace(" ", "");

                    <li style="border: 1px solid white;margin-right: 20px;margin-left: 10px;border-radius: 3px;margin-top: 10px;">
                        <a style="color: white;font-size: 12px;font-weight: bold;font-style: oblique" data-toggle="collapse" href="#@urlLink" class="collapsed" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                            <p>
                                <b class="caret"></b>
                                @MenuList.Key

                            </p>
                        </a>
                        <div style="border:; padding: 2px;" class="collapse" id="@urlLink" aria-expanded="false" style="height: 0px;">
                            <ul class="nav">

                                @foreach (var subMenuList in MenuList)
                                {
                                    <li style="color: white">
                                        <i class="fa fa-toggle-on" style="font-size: 12px;"></i>
                                        <a style="color: white; text-decoration:;" href="@Url.Action(subMenuList.ActionName, subMenuList.ControllerName)">
                                            @subMenuList.SubMenuName
                                        </a>
                                    </li>
                                }

                            </ul>
                        </div>
                    </li>






                }


            }




        </ul>

    </div>
</div>