WCTS/WCTS/Models/EntityModel/ProductionSetup.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCTS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionSetup
    {
        public long Id { get; set; }
        public Nullable<long> LineId { get; set; }
        public string LineName { get; set; }
        public string ShiftId { get; set; }
        public string ShiftName { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public Nullable<long> ModelId { get; set; }
        public string ModelName { get; set; }
        public Nullable<long> InventoryTypeId { get; set; }
        public string InventoryType { get; set; }
        public string ItemCode { get; set; }
        public string LotNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> DeactivateBy { get; set; }
        public Nullable<System.DateTime> DeactivateDate { get; set; }
        public string Target { get; set; }
    }
}

WCTS/WCTS/Controllers/ProductionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCMS_MAIN.HelperClass;
using WCTS.Helper_Model;
using WCTS.Models;
using WCTS.Models.ApiModels;
using WCTS.Models.EntityModel;
using WCTS.Repository;

namespace WCTS.Controllers
{
    public class ProductionController : Controller
    {
        //
        // GET: /Production/
        readonly Dictionary<int, SessionData> _sessiondictionary = SessionData.GetSessionValues();
        readonly ProductionRepository _productionRepository = new ProductionRepository();
        readonly Repository.Common _common = new Repository.Common();
        private readonly NotificationRepository _notificationRepository = new NotificationRepository();
        readonly MasterBarcodeLogRepository _masterBarcodeRepository = new MasterBarcodeLogRepository();
        public ActionResult Index()
        {

            var userId = (long)_sessiondictionary[1].Id;
            var userName = _sessiondictionary[2].Name;



            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            var employeeId = _sessiondictionary[3].Name;
            var model = _sessiondictionary[4].Name;
            var shiftId = _sessiondictionary[5].Name;
            var shiftName = _sessiondictionary[6].Name;
            var categoryCode = _sessiondictionary[7].Name;
            var lineId = _sessiondictionary[8].Id;
            var inventoryType = _sessiondictionary[13].Name;
            var itemCode = _sessiondictionary[10].Name;
            var lotBarcode = _sessiondictionary[11].Name;
            var lineName = _sessiondictionary[9].Name;
            var productionDate = _sessiondictionary[14].Name;
            ViewBag.Model = model;
            ViewBag.ShiftName = shiftName;
            ViewBag.LineName = lineName;
            ViewBag.CategoryCode = categoryCode;
            ViewBag.CategoryCode = categoryCode;
            ViewBag.InventoryType = inventoryType;
            ViewBag.ProductionDate = Convert.ToDateTime(productionDate).ToString("dd-MM-yyyy");
            var masterBarcode = _masterBarcodeRepository.GetMasterBarcode(userId.ToString(), lotBarcode, itemCode, model);
            if (masterBarcode != null)
            {
                ViewBag.MasterBarcode = masterBarcode.MasterBarcode;
            }

            return View();
        }


        [HttpGet]
        public JsonResult GenrateMasterBarcode()
        {
            var userId = (long)_sessiondictionary[1].Id;
            var userName = _sessiondictionary[2].Name;

            if (userId == 0)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            var employeeId = _sessiondictionary[3].Name;
            var model = _sessiondictionary[4].Name;
            var shiftId = _sessiondictionary[5].Name;
            var shiftName = _sessiondictionary[6].Name;
            var categoryCode = _sessiondictionary[7].Name;
            var lineId = _sessiondictionary[8].Id;
            var inventoryType = _sessiondictionary[13].Name;
            var itemCode = _sessiondictionary[10].Name;
            var lotBarcode = _sessiondictionary[11].Name;
            var lineName = _sessiondictionary[9].Name;
            var productionDate = _sessiondictionary[14].Name;
            MasterBarcodeLog masterBarcode = new MasterBarcodeLog();
            masterBarcode.UserId = userId.ToString();
            masterBarcode.ItemCode = itemCode;
            masterBarcode.LotBarcode = lotBarcode;
            masterBarcode.Model = model;
            bool isGenerated = _masterBarcodeRepository.AddMasterBarcode(masterBarcode);
            return Json(isGenerated, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ModelSetup()
        {

            var userId = (long)_sessiondictionary[1].Id;
            var userName = _sessiondictionary[2].Name;
            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }


            return View();
        }

        public ActionResult QcReturnPrint()
        {

            var userId = (long)_sessiondictionary[1].Id;
            var userName = _sessiondictionary[2].Name;
            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }


            return View();
        }


        public ActionResult AdminPassword()
        {

            var userId = (long)_sessiondictionary[1].Id;
            var userName = _sessiondictionary[2].Name;
            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }


            return View();
        }




        [OutputCache(NoStore = true, Location = System.Web.UI.OutputCacheLocation.Client, Duration = 2)]
        public ActionResult GetBrandNotification(string type)
        {

            var userId = (long)_sessiondictionary[1].Id;
            var userName = _sessiondictionary[2].Id;
            var roleId = _sessiondictionary[5].Id;

            object recentnotifications = null;

            return PartialView("_PartialNotification");
        }

        public ActionResult ManualProduction()
        {

            var userId = (long)_sessiondictionary[1].Id;
            var userName = _sessiondictionary[2].Name;
            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }
            var employeeId = _sessiondictionary[3].Name;
            var model = _sessiondictionary[4].Name;
            var shiftId = _sessiondictionary[5].Name;
            var shiftName = _sessiondictionary[6].Name;
            var categoryCode = _sessiondictionary[7].Name;
            var lineId = _sessiondictionary[8].Id;
            var inventoryType = _sessiondictionary[13].Name;
            var itemCode = _sessiondictionary[10].Name;
            var lotBarcode = _sessiondictionary[11].Name;
            var lineName = _sessiondictionary[9].Name;
            var productionDate = _sessiondictionary[14].Name;
            ViewBag.Model = model;
            ViewBag.ShiftName = shiftName;
            ViewBag.LineName = lineName;
            ViewBag.CategoryCode = categoryCode;
            ViewBag.InventoryType = inventoryType;
            ViewBag.ProductionDate = Convert.ToDateTime(productionDate).ToString("dd-MM-yyyy");
            var masterBarcode = _masterBarcodeRepository.GetMasterBarcode(userId.ToString(), lotBarcode, itemCode, model);
            if (masterBarcode != null)
            {
                ViewBag.MasterBarcode = masterBarcode.MasterBarcode;
            }
            return View();
        }

        public ActionResult ProductionSetup()
        {

            var userId = (long)_sessiondictionary[1].Id;
            var userName = _sessiondictionary[2].Name;
            var employeeId = _sessiondictionary[3].Name;
            var model = _sessiondictionary[4].Name;
            var shiftId = _sessiondictionary[5].Name;
            var shiftName = _sessiondictionary[6].Name;
            var categoryCode = _sessiondictionary[7].Name;
            var lineId = _sessiondictionary[8].Id;
            var lineName = _sessiondictionary[9].Name;


            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }
            else
            {
                ViewBag.Model = model;
                ViewBag.ShiftName = shiftName;
                ViewBag.LineName = lineName;
                ViewBag.CategoryCode = categoryCode;


                return View();
            }

        }


        public JsonResult InsertModelName(Model model)
        {
            var userId = (long)_sessiondictionary[1].Id;
            var empId = _sessiondictionary[3].Name;
            var result = new Result();
            if (userId != 0)
            {
                try
                {


                    var isModelExists = _common.GetModels().FirstOrDefault(a => a.ModelName == model.ModelName);

                    if (isModelExists == null)
                    {
                        model.FGItemCode = model.FGItemCode;
                        model.SFGItemCode = model.SFGItemCode;
                        model.AddedBy = empId;
                        model.AddedDate = DateTime.Now;
                        result.IsSuccess = _productionRepository.InsertModelName(model);
                    }

                    else
                    {
                        result.IsSuccess = false;
                        result.Message = "Model Already Added ! Please Update Information If Nedded";

                    }


                    return Json(result);
                }
                catch (Exception ex)
                {
                    throw ex;

                }
            }
            else
            {
                return Json(new Result { Id = "0" });
            }
        }

        public JsonResult UpdateModelInformation(Model model)
        {
            var userId = (long)_sessiondictionary[1].Id;
            var empId = _sessiondictionary[3].Name;
            var result = new Result();
            if (userId != 0)
            {
                try
                {

                    var isExist = _common.GetModels().FirstOrDefault(a => a.ModelName == model.ModelName);

                    if (isExist == null)
                    {
                        result.IsSuccess = false;
                        result.Message = "Model Not Found";
                    }

                    else
                    {
                        isExist.FGItemCode = model.FGItemCode;
                        isExist.SFGItemCode = model.SFGItemCode;
                        isExist.UpdatedBy = empId;
                        isExist.UpdatedDate = DateTime.Now;

WCTS/WCTS/Views/Production/AdminPassword.cshtml
@{
    ViewBag.Title = "AdminPassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="content">
    <div class="row">

        <div class="col-md-6">
            <div class="card card-user">
                <div class="card-header">
                    <h5 class="card-title">Search And Reset Password</h5>
                </div>
                <div class="card-body">
                    <form>

                        <div class="row">
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <label>Employee Id</label>
                                    <input type="text" id="txtEmployeeId" class="form-control" placeholder="Type EmployeeId">

                                </div>

                            </div>

                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <br />
                                    <button type="button" id="btnSearch" class="btn btn-primary btn-border">Search</button>

                                </div>
                            </div>
                        </div>


                    </form>
                </div>
            </div>
        </div>

 
        <div class="col-md-6" id="divInfo" style="display: none">
            <div class="card card-user">
                <div class="card-header">
                    <h5 class="card-title">Employee Info</h5>
                </div>
                <div class="card-body">
                    <form>

                        <div class="row">
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <label>Employee Id</label>
                                    <input type="text" id="txtEmployeeIdChange" class="form-control" placeholder="Type EmployeeId">

                                </div>

                            </div>
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <label>Old Password</label>
                                    <input type="text" id="txtOldPassword" class="form-control" placeholder="Type Old Password">

                                </div>

                            </div>
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <label>New Password</label>
                                    <input type="text" id="txtNewPassword" class="form-control" placeholder="Type New Password">

                                </div>

                            </div>

                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <br />
                                    <button type="button" id="btnUpdate" class="btn btn-primary btn-border">Update Password</button>

                                </div>





                            </div>
                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<link href="~/Scripts/Choosen/chosen.css" rel="stylesheet" />
<link href="~/Scripts/Choosen/chosen-bootstrap.css" rel="stylesheet" />
<link href="~/Content/Jquery-ui-1.12.1.css" rel="stylesheet" />
<script src="~/Scripts/Choosen/chosen.jquery.min.js"></script>
<script src="~/Scripts/DatatablePrint/jquery-ui-1.12.1.js"></script>

<script>

    $("#btnSearch").click(function() {        

        if ($('#txtEmployeeId').val() == "") {
            iziToast.warning({
                timeout: 1500,
                imageWidth: 30,
                position: 'center',
                message: ' Please type Employee Id',
                title: 'warning! -',
                backgroundColor: '#E22919',
                theme: 'dark', // dark
                progressBarColor: '#091B2B',
                titleSize: 15,
                messageColor: '#F4F3F8',
                messageSize: 15,
            });
            return false;
        } else {

            var login = {};
            login.EmployeeId = $('#txtEmployeeId').val();
            $.ajax({
                url: '@Url.Action("GetEmployeeInfoById", "Production")',
                type: 'POST',
                data: JSON.stringify({ login: login }),
                dataType: 'json',
                async: false,
                contentType: 'application/json',
                success: function(result) {

                    console.log(result);
                    if (result.EmployeeId != null) {

                        $("#divInfo").show();
                        $("#txtEmployeeIdChange").val(result.EmployeeId);
                        $("#txtOldPassword").val(result.OldPassword);

                    } else if (result.Id == "0") {
                        window.location = '@Url.Action("LogOut", "Account")';
                    }
                    else {
                        iziToast.warning({
                            timeout: 1500,
                            imageWidth: 30,
                            position: 'center',
                            message: ' No Data Found !',
                            title: 'warning! -',
                            backgroundColor: '#E22919',
                            theme: 'dark', // dark
                            progressBarColor: '#091B2B',
                            titleSize: 15,
                            messageColor: '#F4F3F8',
                            messageSize: 15,
                        });
                        return false;
                    }


                },
                error: function (request) {
                    alert(request.responseText);
                }

            });



        }
    });




    $("#btnUpdate").click(function () {

        if ($('#txtEmployeeIdChange').val() == "") {
            iziToast.warning({
                timeout: 1500,
                imageWidth: 30,
                position: 'center',
                message: ' Please type Employee Id',
                title: 'warning! -',
                backgroundColor: '#E22919',
                theme: 'dark', // dark
                progressBarColor: '#091B2B',
                titleSize: 15,
                messageColor: '#F4F3F8',
                messageSize: 15,
            });
            return false;
        }

        else if ($('#txtOldPassword').val() == "") {
            iziToast.warning({
                timeout: 1500,
                imageWidth: 30,
                position: 'center',
                message: ' Please type Old Password',
                title: 'warning! -',
                backgroundColor: '#E22919',
                theme: 'dark', // dark
                progressBarColor: '#091B2B',
                titleSize: 15,
                messageColor: '#F4F3F8',
                messageSize: 15,
            });
            return false;

        }
        else if ($('#txtNewPassword').val() == "") {
            iziToast.warning({
                timeout: 1500,
                imageWidth: 30,
                position: 'center',
                message: ' Please type New Password',
                title: 'warning! -',
                backgroundColor: '#E22919',
                theme: 'dark', // dark
                progressBarColor: '#091B2B',
                titleSize: 15,
                messageColor: '#F4F3F8',
                messageSize: 15,
            });
            return false;

        }


        else {
            var logindata = {};

            logindata.EmployeeId = $("#txtEmployeeId").val();
            logindata.OldPassword = $("#txtOldPassword").val();
            logindata.NewPassword = $("#txtNewPassword").val();
            console.log(logindata);
            $.ajax({
                url: '@Url.Action("ChangePasswordDetails", "Production")',
                type: 'Post',
                data: JSON.stringify({ login: logindata }),
                dataType: 'json',
                async: false,
                contentType: 'application/json',
                success: function (result) {
                    if (result.IsSuccess) {
                        iziToast.success({
                            timeout: 2000,
                            imageWidth: 150,
                            position: 'center',
                            title: 'Success',
                            message: result.Message
                        });

                        @*setTimeout(function () {
                            window.location.href = "@Url.Action("LogOut", "Account")";
                        }, 1000);*@

                    }
                    else if (result.Id == "0") {
                        window.location = '@Url.Action("LogOut", "Account")';

                    } else {

                        iziToast.success({
                            timeout: 2000,
                            imageWidth: 150,
                            position: 'center',
                            title: 'Success',
                            message: result.Message
                        });
                        return false;
                    }

                },
                error: function (request) {
                    alert(request.responseText);
                }

            });


        }
    });

</script>