WCTS/WCTS/Controllers/UpdatePanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCMS_MAIN.HelperClass;
using WCTS.Helper_Model;
using WCTS.Models.EntityModel;
using WCTS.Repository;

namespace WCTS.Controllers
{
    public class UpdatePanelController : Controller
    {
        private readonly Dictionary<int, SessionData> _sessiondictionary = SessionData.GetSessionValues();
        private readonly ProductionRepository _productionRepository = new ProductionRepository();
        private readonly ReportRepository _reportRepository = new ReportRepository();
        private readonly UpdatePanelRepository _updatePanelRepository = new UpdatePanelRepository();
        private readonly Repository.Common _common = new Repository.Common();
        public ActionResult Update()
        {
            var userId = (long)_sessiondictionary[1].Id;
          
            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }

        #region Gomu Gomu testo Codeeeeeeeee
        //Gomu Gomu testo Codeeeeeeeee//

        public ActionResult CheckSerial()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }

        public JsonResult CheckSerialCode(string barCode)
        { 
            var result = new Result();

             var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {
                result.Id = "0";
                return Json(result);
            }

            else
            {    
            var codedata = _updatePanelRepository.CheckSerialCode(barCode);

                if (codedata != null)
                {
                    result.Id = "1";
                    result.Message = "Serial Found"; 
                }

                else
                {
                    result.Id = "2";
                    result.Message = "Serial Not Found Found"; 
                }

            return Json(result, JsonRequestBehavior.AllowGet);

                
            }

       
        }

        //Gomu Gomu testo Codeeeeeeeee//
        #endregion Gomu Gomu testo Codeeeeeeeee

        public JsonResult GetBarcodeInforForUpdate(string barCode)
        {
            var codedata = _reportRepository.GetBarcodeDetailsReport(barCode);
           
            return Json(codedata.Cast<object>().ToArray(), JsonRequestBehavior.AllowGet);

        }


        public JsonResult ModifyCompressorBarcodeinfo(ProductionMaster productionMaster, string clickType)
        {

            var userId = (long)_sessiondictionary[1].Id;
            var result = new Result();
            if (userId != 0)
            {
                try
                {
                    if (clickType == "Update")

                    {
                        productionMaster.UpdatedBy = userId;
                        result.IsSuccess = _updatePanelRepository.UpdateProductionMaster(productionMaster);

                    }
                    if (clickType == "Delete")
                    {
                        result.IsSuccess = _updatePanelRepository.DeleteProductionMaster(productionMaster);

                    }

                   
                    return Json(result, JsonRequestBehavior.AllowGet);

                }
                catch (Exception exception)
                {
                    result.IsSuccess = false;
                    result.Message = exception.ToString();
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            return Json(new Result { Id = "0" });
        }




	}
}

WCTS/WCTS/Views/UpdatePanel/CheckSerial.cshtml
@{
    ViewBag.Title = "CheckSerial";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-5">
                <div class="card card-chart" style="text-align: center; border: 1px solid #DC2366 !important">
                    <div class="card-header card-header-rose">
                        Scan Serial
                    </div>
                    <div class="card-body">
                        <input id="txtCode" style="height: 50px; font-size: 20px; border: 3px solid #9730b0" type="text" placeholder=" Scan Serial" class="form-control form-control-success">
                    </div>

                </div>
            </div>
            
            
            
            <div class="col-md-5" id="idShow" style="display: none;font-size: 30px;font-weight: bold;text-align: center;vertical-align: middle">
               
            </div>

        </div>
    </div>
</div>
<link href="~/Content/iziToast.min.css" rel="stylesheet" />
<script src="~/Scripts/jqueryprint/jquery.min.js"></script>
<script src="~/Scripts/jqueryprint/jQuery.print.min.js"></script>
<script src="~/Scripts/Barcode.js"></script>
<script src="~/Scripts/iziToast.min.js"></script>
<script>
    $(function () {

        $("#txtCode").focus();
    });



    $("#txtCode").on('keydown', function (e) {

        debugger;
        if ($("#txtCode").val().length == 13) {
            var code = $("#txtCode").val();
            $.ajax({
                url: '@Url.Action("CheckSerialCode", "UpdatePanel")',
                type: 'Post',
                data: JSON.stringify({ barcode: code }),
                dataType: 'json',
                async: false,
                contentType: 'application/json',
                success: function (data) {


                    if (data.Id == "1") {
                        $("#idShow").show();
                        $("#idShow").css("background-color", "green");
                        $("#idShow").text(data.Message);
                        $("#idShow").css("color", "white");
                        $("#txtCode").focus();
                        $("#txtCode").val('');
                        
                        $("#idShow").fadeOut(2100);
                    }
                    
                    if (data.Id == "2") {
                        $("#idShow").show();
                        $("#idShow").css("background-color", "red");
                        $("#idShow").text(data.Message);
                        $("#idShow").css("color", "white");
                        $("#txtCode").focus();
                        $("#txtCode").val('');
                        $("#idShow").fadeOut(2100);
                    }

                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log('Error in Operation');
                }
            });
        }

    });

    </script>