WCTS/WCTS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCMS_MAIN.HelperClass;
using WCTS.Repository;

namespace WCTS.Controllers
{
    public class HomeController : Controller
    {
        
readonly Dictionary<int, SessionData> _sessiondictionary = SessionData.GetSessionValues();
        readonly ProductionRepository _productionRepository = new ProductionRepository();
        readonly Repository.Common _common = new Repository.Common();
        public ActionResult Index()
        {
            var userId = (long)_sessiondictionary[1].Id;
            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            else
            {
                var model = _sessiondictionary[4].Name;
                var shiftName = _sessiondictionary[6].Name;
                var categoryCode = _sessiondictionary[7].Name;
                var inventoryType = _sessiondictionary[13].Name;
                var lineName = _sessiondictionary[9].Name;
                ViewBag.Model = model;
                ViewBag.ShiftName = shiftName;
                ViewBag.LineName = lineName;
                ViewBag.CategoryCode = categoryCode;

                ViewBag.InventoryType = inventoryType;
                return View();
            }
         
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult SessionDummy()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        [HttpPost]
        public JsonResult KeepSessionAlive()
        {
            return new JsonResult { Data = "Success" };
        }

    }
}

WCTS/WCTS/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Antlr.Runtime;
using Newtonsoft.Json;
using WCMS_MAIN.HelperClass;
using WCTS.Models;
using WCTS.Models.ApiModels;
using WCTS.Models.EntityModel;
using WCTS.Repository;
using ProductionModel = WCTS.Models.ProductionModel;

namespace WCTS.Controllers
{
    public class ReportController : Controller
    {
        //
        // GET: /Report/
        private readonly Dictionary<int, SessionData> _sessiondictionary = SessionData.GetSessionValues();
        private readonly ProductionRepository _productionRepository = new ProductionRepository();
        private readonly ReportRepository _reportRepository = new ReportRepository();
        private readonly Repository.Common _common = new Repository.Common();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DailyProduction()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }

        public ActionResult BarCodeTracking()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }

        public ActionResult FinalInventory()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }

        public ActionResult LotTracking()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }


        public ActionResult MasterBarcodeTracking()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }

        public ActionResult OracleUploadReport()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }




        public ActionResult HoldReport()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }


        public ActionResult RejectedReport()
        {

            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();

           
        }
        public ActionResult QcLotTrackingReport()
        {

            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();


        }



        public ActionResult AllProduction()
        {

            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();


        }

        public ActionResult ManualPrintLog()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }


        public ActionResult MultiBarcodeReport()
        {
            var userId = (long)_sessiondictionary[1].Id;

            if (userId == 0)
            {

                return RedirectToAction("LogOut", "Account");
            }

            return View();
        }

        [HttpPost]
        public JsonResult GetProductionMultiBarcodeData(string strdata)
        {
            var modelData = JsonConvert.DeserializeObject<List<ProductionModel>>(strdata);
            var data = _productionRepository.GetProductionMultiBarcodeData(modelData);
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }




        public JsonResult GetProductionLine(string fromdate, string todate)
        {

            var list = _reportRepository.GetProductionLineReport(fromdate, todate).ToList();

              var overAlllist = new List<Models.ProductionModel>();

            foreach (var items in list)
            {
                var overAlll = new Models.ProductionModel();

                overAlll.DateTime = items.Date.ToString("yyyy-MM-dd");
                overAlll.Model = items.Model;
                overAlll.ShiftName = items.ShiftName;
                overAlll.CategoryName = items.CategoryName;
                overAlll.Status = "Passed";
                overAlll.Total = items.Total;

                overAlllist.Add(overAlll);
            }

            return Json(new { data = overAlllist }, JsonRequestBehavior.AllowGet);


        }
        

        public JsonResult GetCurrentlyHoldReport()
        {

            var list = _reportRepository.GetCurrentlyHoldReport();
            // list.GroupBy(x => new {x.LotBarcode, x.Model, x.ProductionDate}).Select(n => new ProductionModel
            var overAlllist =
                list.Select(n => new ProductionModel
                {
                    BarCode = n.Barcode,
                    MasterBarCode = n.MasterBarcode,
                    LotNo = n.LotBarcode,
                    DateTime = Convert.ToDateTime(n.ProductionDate).ToString("dd-MM-yyyy"),
                    Model=n.Model,
                    Status = "Hold",
                    //Total = n()
                }).ToList();

            return Json(new { data = overAlllist }, JsonRequestBehavior.AllowGet);


        }


        public JsonResult GetQcPassedOracleUploadedData(DateTime fromdate, DateTime todate)
        {

            var list = _reportRepository.GetQcPassedOracleUploadedData(fromdate, todate).ToList();

            //var list = reportService.GetLogisticsReportByDate(fromdate, todate).Where(a => a.Uploaded == null).ToList();

            var oQcListByDate = list.GroupBy(x => new { x.Model, x.LotBarcode, x.OracleTransactionCode }).Select(n => new QcItemsModel()
            {
                Model = n.Key.Model,
                LotBarcode = n.Key.LotBarcode,
                OracleTransactionCode = n.Key.OracleTransactionCode,
                QcPassedCount = n.Count(),
                OracleUploadCount = n.Count(a => a.OracleUploaded == true)
            }).ToList();

            return Json(oQcListByDate, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllHoldReport(string fromdate, string todate)
        {

            var list = _reportRepository.GetAllHoldReport(fromdate, todate);
            var overAlllist =
                list.Select(n => new ProductionModel
                {
                    LotNo = n.LotNumber,
                    BarCode = n.BarCode,
                    MasterBarCode = n.MasterBarcode,
                    DateTime = Convert.ToDateTime(n.ProductionDate).ToString("dd-MM-yyyy"),
                    ScanDateTime = Convert.ToDateTime(n.AddedDate).ToString("dd-MM-yyyy"),
                    Model = _common.GetProductionSetupDataByLotAndSerial(new ProductionSetup(){LotNumber = n.LotNumber, SerialNumber =n.LotTrackingSerial }).ModelName,
                    Status = "Holded",
                    Remarks = n.Remarks
                    //Total = _common.GetProductionDataDataByLotAndSerial(new ProductionSetup() { LotNumber = n.LotNumber, SerialNumber = n.LotTrackingSerial }).Count(),
                }).ToList();

            return Json(new { data = overAlllist }, JsonRequestBehavior.AllowGet);


        }
        public JsonResult GetAllRejectedReport(string fromdate, string todate)
        {

            var list = _reportRepository.GetAllRejectedReport(fromdate, todate);
            var overAlllist =
                list.Select(n => new ProductionModel
                {
                    LotNo = n.LotNumber,
                    BarCode = n.BarCode,
                    MasterBarCode = n.MasterBarcode,
                    DateTime = Convert.ToDateTime(n.ProductionDate).ToString("dd-MM-yyyy"),
                    ScanDateTime = Convert.ToDateTime(n.AddedDate).ToString("dd-MM-yyyy"),
                    Model = _common.GetProductionSetupDataByLot(new ProductionSetup() { LotNumber = n.LotNumber }).ModelName ?? "NULL",
                    Status = "Rejected",
                    Remarks = n.Remarks
                    //Total = _common.GetProductionDataDataByLotAndSerial(new ProductionSetup() { LotNumber = n.LotNumber, SerialNumber = n.LotTrackingSerial }).Count(),
                }).ToList();

            return Json(new { data = overAlllist }, JsonRequestBehavior.AllowGet);


        }

        public JsonResult GetCurrentlyRejectedReport()
        {

            var list = _reportRepository.GetCurrentlyRejectedReport();
            // list.GroupBy(x => new {x.LotBarcode, x.Model, x.ProductionDate}).Select(n => new ProductionModel
            var overAlllist =
                list.Select(n => new ProductionModel
                {
                    BarCode = n.BarCode,
                    MasterBarCode = n.MasterBarcode,
                    LotNo = n.LotNumber,
                    DateTime = Convert.ToDateTime(n.ProductionDate).ToString("dd-MM-yyyy"),

WCTS/WCTS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WCTS/WCTS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WCTS/WCTS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #chartdiv {
        width: 100%;
        height: 500px;
    }
</style>
<div class="row">

    @*<div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-body ">
                    <div class="row">
                        <div class="col-2 col-md-4">
                            <div class="icon-big text-center icon-warning">
                                <i class="nc-icon nc-globe text-warning"></i>
                            </div>
                        </div>
                        <div class="col-10 col-md-8">
                            <div class="numbers">
                                <p class="card-category">Running Model</p>
                                <p class="card-title">
                                    @ViewBag.Model-(@ViewBag.CategoryCode)
                                </p><p>
                                    </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <hr>
                    <div class="stats">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-body ">
                    <div class="row">
                        <div class="col-2 col-md-4">
                            <div class="icon-big text-center icon-warning">
                                <i class="nc-icon nc-money-coins text-success"></i>
                            </div>
                        </div>
                        <div class="col-10 col-md-8">
                            <div class="numbers">
                                <p class="card-category">Running Shift</p>
                                <p class="card-title">
                                    @ViewBag.ShiftName
                                </p><p>
                                    </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <hr>
                    <div class="stats">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-body ">
                    <div class="row">
                        <div class="col-2 col-md-4">
                            <div class="icon-big text-center icon-warning">
                                <i class="nc-icon nc-vector text-danger"></i>
                            </div>
                        </div>
                        <div class="col-10 col-md-8">
                            <div class="numbers">
                                <p class="card-category">Invrntory Type</p>
                                <p class="card-title">
                                    @ViewBag.InventoryType
                                </p><p>
                                    </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <hr>
                    <div class="stats">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-body ">
                    <div class="row">
                        <div class="col-5 col-md-4">
                            <div class="icon-big text-center icon-warning">
                                <i class="nc-icon nc-favourite-28 text-primary"></i>
                            </div>
                        </div>
                        <div class="col-7 col-md-8">
                            <div class="numbers">
                                <p class="card-category">Followers</p>
                                <p class="card-title">
                                    +45K
                                </p><p>
                                    </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <hr>
                    <div class="stats">

                    </div>
                </div>
            </div>
        </div>*@




    <div class="col-md-12">
        <div class="card col-md-12 ">
            <div class="card-header ">
                <h5 class="card-title">Production Chart</h5>
                <p class="card-category">Last Seeven Days production</p>
            </div>
            <div class="card-body ">
                <div id="chartdiv"></div>
            </div>
            <div class="card-footer ">

            </div>
        </div>
    </div>


    @*<div class="col-lg-12 col-md-12 col-sm-12">
            <h2></h2>

        </div>*@
</div>
<link href="~/Content/fontawesome.min.css" rel="stylesheet" />

@*<link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">*@
@*<script src="~/Scripts/jquery.min.js"></script>*@
@*<script src="https://www.amcharts.com/lib/4/core.js"></script>
    <script src="https://www.amcharts.com/lib/4/charts.js"></script>
    <script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>*@
<script src="~/Scripts/Chart/amcore.js"></script>
<script src="~/Scripts/Chart/amchart.js"></script>
<script src="~/Scripts/Chart/amanimated.js"></script>
@**@
<script>

    $(function () {
        GetLastSevenDaysProduction();
    });


    function GetLastSevenDaysProduction() {
        $.ajax({
            url: '  @Url.Action("GetLastSevenDaysProduction", "Report")',
            type: 'GET',
            dataType: 'json',
            async: false,
            contentType: 'application/json',
            success: function (result) {
                GenerateChart(result);
            },
            error: function (result, textStatus, jqXHR) {
                console.log(result);
                return false;
            }
        });


    }
    function GenerateChart(result) {
        debugger;
        am4core.useTheme(am4themes_animated);
        var chart = am4core.create("chartdiv", am4charts.XYChart);
        chart.scrollbarX = new am4core.Scrollbar();

        chart.data = getChartData(result);
        // Create axes
        var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
        categoryAxis.dataFields.category = "Date";
        categoryAxis.renderer.grid.template.location = 0;
        categoryAxis.renderer.minGridDistance = 10;
        categoryAxis.renderer.labels.template.horizontalCenter = "right";
        categoryAxis.renderer.labels.template.verticalCenter = "middle";
        categoryAxis.renderer.labels.template.rotation = 0;
        categoryAxis.tooltip.disabled = false;
        categoryAxis.renderer.minHeight = 100;
        var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
        valueAxis.renderer.minWidth = 50;
        var series = chart.series.push(new am4charts.ColumnSeries());
        series.sequencedInterpolation = true;
        series.dataFields.valueY = "Count";
        series.dataFields.categoryX = "Date";
        //series.tooltipText = "[{categoryX}: bold]Total Production : {Count}  [/]" +
        //    "-------------" +
        //    "  Details" +
        //    "-------------" +
        //    "{Details}";
        series.tooltipHTML = "<center><strong>Total Production : {Count}</strong></center><hr />" +
            "<table>" +
            "<tr>" +
            "<th align='left'></th>" +
            "<td>{Details}</td></tr>" +
            "</table>" +
            "<hr />";
        //series.columns.template.stro
        series.tooltip.pointerOrientation = "vertical";
        series.columns.template.column.cornerRadiusTopLeft = 10;
        series.columns.template.column.cornerRadiusTopRight = 10;

        // on hover, make corner radiuses bigger
        var hoverState = series.columns.template.column.states.create("hover");
        hoverState.properties.cornerRadiusTopLeft = 0;
        hoverState.properties.cornerRadiusTopRight = 0;
        hoverState.properties.fillOpacity = 1;

        series.columns.template.adapter.add("fill", function (fill, target) {
            return chart.colors.getIndex(target.dataItem.index);
        });

        // Cursor
        chart.cursor = new am4charts.XYCursor();






    }

    function getChartData(chartdata) {
        debugger;
        var chartData = [];


        $.each(chartdata, function (index, itemData) {

            chartData.push({
                "Date": itemData.Date,
                "Count": itemData.Count,
                "Details": itemData.OverAllData
            });
            //chart.validateData();
        });
        return chartData;
    }
</script>

WCTS/WCTS/Views/Home/SessionDummy.cshtml
@{
    ViewBag.Title = "SessionDummy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<script>
    debugger;

    var keepSessionAlive = false;
    var keepSessionAliveUrl = null;

    function SetupSessionUpdater(actionUrl) {
        debugger;
        keepSessionAliveUrl = actionUrl;
        var container = $("#body");
        container.mousemove(function () { keepSessionAlive = true; });
        container.keydown(function () { keepSessionAlive = true; });
        CheckToKeepSessionAlive();
    }

    function CheckToKeepSessionAlive() {
        debugger;
       // setTimeout(KeepSessionAlive(), 30000);
        KeepSessionAlive();
    }

    function KeepSessionAlive() {
        debugger;
        if (keepSessionAlive) {
            $.ajax({
                type: "POST",
                url:'@Url.Action("KeepSessionAlive", "Home")',
                success: function () { keepSessionAlive = false; }
            });
        }
       //CheckToKeepSessionAlive();
    }
    setInterval(function () { SetupSessionUpdater(); }, 30000);
    
    //setInterval(SetupSessionUpdater('@Url.Action("KeepSessionAlive", "Home")'), 20000);
    
   

</script>*@